name: Build Webapp
on:
  push:
    branches: [ master ]
    paths: 
    - TabooWebapp/**
  pull_request:
    branches: [ master ]
    paths: 
    - TabooWebapp/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: npm install
      working-directory: TabooWebapp/
    - name: Build
      run: npm run build
      working-directory: TabooWebapp/
    
