name: Build Webapp
on:
  push:
    branches: [ master ]
    paths: 
    - TabooWebapp/**
    - .github/**
  pull_request:
    branches: [ master ]
    paths: 
    - TabooWebapp/**
    - .github/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: npm install
      working-directory: TabooWebapp/
    - name: Build
      run: npm run build
      env:
        VUE_APP_PUBIC_PATH: "./infinite-taboo"
      working-directory: TabooWebapp/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: TabooWebapp/dist
    
